# Generated by Django 6.1 on 2026-09-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_subcategory_product_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('no_size', 'No size'), ('clothing', 'Clothing sizes'), ('free_size', 'Free size')], default='no_size', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('no_size', 'No size'), ('s', 'S'), ('xl', 'XL'), ('xxl', 'XXL'), ('free_size', 'Free Size')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='store.product')),
            ],
            options={
                'verbose_name': 'product inventory',
                'verbose_name_plural': 'product inventory',
                'constraints': [models.UniqueConstraint(fields=('product', 'size'), name='unique_size_per_product')],
            },
        ),
    ]
