# Generated by Django 6.1 on 2026-10-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_images_product_image_1_product_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('free_size', 'Free size'), ('no_size', 'No size'), ('clothing', 'Clothing sizes')], default='no_size', max_length=20),
        ),
    ]
