# Generated by Django 6.1 on 2026-10-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_size_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_type',
            field=models.CharField(choices=[('free_size', 'Free size'), ('no_size', 'No size'), ('clothing', 'Clothing sizes')], default='free_size', max_length=20),
        ),
    ]
