# Generated by Django 6.1 on 2026-10-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_category_description_subcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/hero')),
                ('alt_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'hero poster',
                'verbose_name_plural': 'hero posters',
                'ordering': ('-pk',),
            },
        ),
    ]
